### ISSUE TITLE
Crash on dynamic deletion of instances of Roles

### ISSUE THREAD

**Issue by bzEq** [fizzbee-io/fizzbee#136]
The sample code in https://fizzbee.io/tutorials/roles/#dynamic-role-creation-and-deletion crashes in the playground
```
Output
Model checking BuzzyMcBee.json
configFileName: fizz.yaml
StateSpaceOptions: options:{max_actions:100 max_concurrent_actions:2 crash_on_yield:true} liveness:"strict" deadlock_detection:true

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x743149]

goroutine 1 [running]:
github.com/fizzbee-io/fizzbee/lib.(*Role).RefStringShort(...)
	lib/starlark_role.go:138
github.com/fizzbee-io/fizzbee/modelchecker.(*Processor).scheduleAction(0xc000210580, 0xc000067080, 0xc0000abe14?, 0xc000015a40, 0x0, 0xc0000afc80, 0x1)
	modelchecker/processor.go:1514 +0x289
github.com/fizzbee-io/fizzbee/modelchecker.(*Processor).scheduleRoleActions(0xc000210580, 0xc000067080, 0x0)
	modelchecker/processor.go:1457 +0x24a
github.com/fizzbee-io/fizzbee/modelchecker.(*Processor).YieldNode(0xc000210580, 0xc000067080)
	modelchecker/processor.go:1440 +0x510
github.com/fizzbee-io/fizzbee/modelchecker.(*Processor).processNode(0xc000210580, 0xc000067080)
	modelchecker/processor.go:1297 +0xb78
github.com/fizzbee-io/fizzbee/modelchecker.(*Processor).Start(0xc000210580)
	modelchecker/processor.go:981 +0x4ad
main.startModelChecker({0xc000024060?, 0xc000151f00?}, 0xc000210580)
	main.go:299 +0xae
main.main()
	main.go:161 +0xf13
```

**Comment by jp-fizzbee** [comment]
Fixed in https://github.com/fizzbee-io/fizzbee/pull/140
